version: '2'

services:
  bmp:
    image: openlmis/bmp

  funtest:
    image: openlmis/bzt-yarn
    environment:
      BMP_PRESENT: 'true' # for our wdio.conf.js
      DISPLAY_ID: '1001'
    volumes:
      - './:/bzt-configs'
      - './build/bzt-artifacts:/tmp/artifacts'
      - './resources:/tmp/resources'
    entrypoint: '/bin/bash'
    command: 'testWithTaurusAndBmp.sh'
    depends_on:
      - bmp
